# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: selectmarkets
    ports:
      - "5433:5432"

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis-select
    ports:
      - "6379:6379"
